### ISSUE TITLE
Todo list to track

### ISSUE THREAD

**Issue by mathanamathav** [drMy5tery/Trust-Me-Bro#1]
- [x] Develop the ML model to classify the given video is valid or not ,with top 500 comments as the input
- [x] ML model deployment
- [x] Deploy the API in vercel / any free hosting
- [x] Develop/deploy web extension
- [ ] Possible ideas to extend this idea

**Comment by mathanamathav** [comment]
@drMy5tery

**Comment by drMy5tery** [comment]
On it

**Comment by drMy5tery** [comment]
Some Minor Validation  or changes and a review check can be done before deploying @mathanamathav

**Comment by mathanamathav** [comment]
# about section content : 
Trust me, bro, is a simple and fun project that aims to eliminate YouTube videos that provide wrong information to users. It relies solely on user comments as input and does not currently take the entire video into consideration. The project's objective is to predict the validity of the video based solely on comments. If you have suggestions for improving the method using better ML models, please reach out to us via email or through the GitHub repository's issues or pull requests. We welcome valid ideas and will consider integrating them into the main project. Please keep in mind that we prefer to utilize free tools and technologies whenever possible.

is this good ?

**Comment by drMy5tery** [comment]
Good one dude 🤌🏻

**Comment by mathanamathav** [comment]
https://github.com/othneildrew/Best-README-Template 

https://github.com/matiassingers/awesome-readme

readme templates @drMy5tery

**Comment by drMy5tery** [comment]
1.Removing Scores from showing in html.
2.Removing unnecessary files
3.Changing the text of summary for "Invalid repsonse"

@mathanamathav

**Comment by drMy5tery** [comment]
Need to configure readme.md for adding API key in environment variable

**Comment by mathanamathav** [comment]
@drMy5tery what happen to extension part of it?

**Comment by drMy5tery** [comment]
UI Completed for web extension, might require some minor changes in future if needed or demanded.

**Comment by mathanamathav** [comment]
GG 
![HappyHappyHappyHappyGIF](https://github.com/drMy5tery/Trust-Me-Bro/assets/62739618/48c32762-0e88-4a2d-be9e-91b2053dcdef)
